version: "3"

services:
  frontend:
    build: ./frontend
    ports:
      - "8080:8080"
    container_name: frontend-docker
    restart: always
    environment:
      - CHOKIDAR_USEPOLLING=true
    links:
      - backend

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    container_name: backend-docker
    restart: always
    environment: 
      - DB_STRING=mongodb://mongodb:27017/service-desk

  mongodb:
    container_name: mongo-dev
    image: mongo
    # environment:
    #   - MONGO_INITDB_ROOT_USERNAME=admin
    #   - MONGO_INITDB_ROOT_PASSWORD=pass
    ports:
      - "27017:27017"

  mongo-express:
    container_name: mongo-express
    image: mongo-express
    depends_on:
      - mongodb
    environment:
      # - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      # - ME_CONFIG_MONGODB_ADMINPASSWORD=pass
      - ME_CONFIG_MONGODB_SERVER=mongo-dev
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=ihavealongpassword
    ports:
      - "8081:8081"
